coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 95%
        threshold: 1%

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "**/minimal_init.lua"
  - "**/*.spec.lua"
  - "pack/**/*"

parsers:
  v1:
    include_full_missed: true
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false

fixes:
  - "/home/runner/work/nvim-repomix/::"